### PR TITLE
Create Dinosaurs

### PR DESCRIPTION
**Pull request by JanneSimonsen**
I think that we need dinosaurs.
This is relevant to #4  - I think...

### CODE REVIEW

**Comment by lars-olsen** [comment]
dinosaurs is boring. A dodo is what we need

**Comment by EES58** [comment]
As one I can only agree

**Comment by lars-olsen** [comment]
vi er ikke færdige med mobbe dino...

**Comment by JanneSimonsen** [comment]
Dino er de sejeste.... Drop de små papegøjer

**Pull request merged**
